// Code generated by "stringer -type=PinMode"; DO NOT EDIT.

package pintable

import "fmt"

const (
	_PinMode_name_0 = "IOAPWMSERVOSHIFTI2CONEWIRESTEPPERENCODERSERIALPULLUP"
	_PinMode_name_1 = "X"
)

var (
	_PinMode_index_0 = [...]uint8{0, 1, 2, 3, 6, 11, 16, 19, 26, 33, 40, 46, 52}
	_PinMode_index_1 = [...]uint8{0, 1}
)

func (i PinMode) String() string {
	switch {
	case 0 <= i && i <= 11:
		return _PinMode_name_0[_PinMode_index_0[i]:_PinMode_index_0[i+1]]
	case i == 127:
		return _PinMode_name_1
	default:
		return fmt.Sprintf("PinMode(%d)", i)
	}
}
